#! /bin/bash
#
# You might encounter trouble installing psychopg2 on a Mac

### Following: https://github.com/psycopg/psycopg2/issues/1200#issuecomment-770198398

brew install openssl
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
pip3 install psycopg2
