#!/bin/bash

clear

source .env

echo -e """${BLU}
================================================================
    RUNNING PIPELINE TO ADD NAME-SEARCH FUNCTIONALITY TO DB

(Hint: add 1-3 numbered args to run subsections of the pipeline)
================================================================
${WHI}"""

sleep 2

# If args aren't provided, assign default values to choice_* vars
# Note syntax: FOO=${VARIABLE:-default}  # If variable not set or null, use default.
choice_lower=${1:-0}
choice_upper=${2:-3}

echo "Running stages "$choice_lower" to "$choice_upper

sleep 2

# function to decide whether or not stage is to be executed
runStage() {
    stage=$1
    [[ -z $1 ]] && echo "runStage must receive an argument" && exit 1

    if [[ $stage -ge $choice_lower && $stage -le $choice_upper ]]; then
        echo true
    else
        echo false
    fi
}

if $(runStage 0); then
    echo -e "${CYA}<<<RUNNING STAGE 0>>>${WHI}"
    python src/nameSearchBuild/stage0.py
    sleep 1
fi

if $(runStage 1); then
    echo -e "${CYA}<<<RUNNING STAGE 1>>>${WHI}"
    python src/nameSearchBuild/stage1.py
    sleep 1
fi

if $(runStage 2); then
    echo -e "${CYA}<<<RUNNING STAGE 2>>>${WHI}"
    python src/nameSearchBuild/stage2.py
    sleep 1
fi

if $(runStage 3); then
    echo -e "${CYA}<<<RUNNING STAGE 3>>>${WHI}"
    python src/nameSearchBuild/stage3.py
    sleep 1
fi
