#! /bin/bash

echo '''

    ======================
    RUNNING PRECOMMIT HOOK
    ======================

'''

if [ true ]; then
    echo """
        Skipping auto-format!!!
    """
else
    # Auto-format all python scripts
    .venv/bin/autopep8 -ir src/**
    .venv/bin/autopep8 -ir tests/**
fi
